version: 2.1

workflows:
  lint:
    jobs:
      - prep-deps
      - test-build:
          requires:
            - prep-deps
      - test-lint:
          requires:
            - prep-deps
            - test-build
      - test-unit:
          requires:
            - prep-deps
      - all-tests-pass:
          requires:
            - test-lint
            - test-unit

jobs:
  prep-deps:
    docker:
      - image: cimg/node:18.18
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            .circleci/scripts/deps-install.sh
      - run:
          name: Collect yarn install HAR logs
          command: |
            .circleci/scripts/collect-har-artifact.sh
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
            - build-artifacts

  test-build:
    docker:
      - image: cimg/node:18.18
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build project
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  test-lint:
    docker:
      - image: cimg/node:18.18
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn lint

  test-unit:
    docker:
      - image: cimg/node:18.18
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Unit tests
          command: yarn test

  all-tests-pass:
    docker:
      - image: cimg/node:18.18
    steps:
      - run:
          name: All tests passed
          command: echo 'Great success'
